"""empty message

Revision ID: 0b10de10a387
Revises: 6986a39db1a7
Create Date: 2017-12-12 01:30:58.219416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b10de10a387'
down_revision = '6986a39db1a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('status', sa.Enum('blocked', 'disabled', 'enabled', 'pending', name='statusenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'status')
    # ### end Alembic commands ###
