"""empty message

Revision ID: 2153789e6bf6
Revises: 75e453f2595c
Create Date: 2017-12-07 12:15:47.037173

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2153789e6bf6'
down_revision = '75e453f2595c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'latitude')
    op.drop_column('User', 'longitude')
    op.add_column('shuttle', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('shuttle', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shuttle', 'longitude')
    op.drop_column('shuttle', 'latitude')
    op.add_column('User', sa.Column('longitude', mysql.FLOAT(), nullable=True))
    op.add_column('User', sa.Column('latitude', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
