"""empty message

Revision ID: 2be951197bde
Revises: 
Create Date: 2017-12-05 09:49:54.001980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2be951197bde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shuttle', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('shuttle', 'shuttle_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shuttle', sa.Column('shuttle_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('shuttle', 'id')
    # ### end Alembic commands ###
