"""empty message

Revision ID: 75e453f2595c
Revises: a15aa574a8cf
Create Date: 2017-12-07 11:31:08.622134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e453f2595c'
down_revision = 'a15aa574a8cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('User', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'longitude')
    op.drop_column('User', 'latitude')
    # ### end Alembic commands ###
