"""empty message

Revision ID: a15aa574a8cf
Revises: 914f84133c73
Create Date: 2017-12-05 11:13:11.496905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a15aa574a8cf'
down_revision = '914f84133c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('type', sa.Enum('building', 'bus_stop', name='locationtypeenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'type')
    # ### end Alembic commands ###
