"""empty message

Revision ID: e2230e63835b
Revises: 0b10de10a387
Create Date: 2017-12-12 01:42:59.004899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2230e63835b'
down_revision = '0b10de10a387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'status',
               existing_type=mysql.ENUM(u'blocked', u'disabled', u'enabled', u'pending'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'status',
               existing_type=mysql.ENUM(u'blocked', u'disabled', u'enabled', u'pending'),
               nullable=True)
    # ### end Alembic commands ###
